#!/bin/zsh

#####################################
##  Shell plugins (~/.oh-my-zsh)
#####################################

# Path to your oh-my-zsh installation.
if [ ! -d ~/.oh-my-zsh ]; then
    sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
fi
export OMZ="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$OMZ/custom"

# Auto-install plugins or themes into the oh-my-zsh custom dir
# $1: short github url, $2: plugins or themes
function Plugin() {
    local giturl=$1  # https://github.com/...
    local basedir=$2 # themes or plugins
    local name=$(basename ${giturl%.*})
    if [ ! -d ${ZSH_CUSTOM}/$basedir/$name ]; then
        git clone "https://github.com/$giturl" ${ZSH_CUSTOM}/$basedir/$name
    fi
}

## Powerlevel9k theme
Plugin "bhilburn/powerlevel9k" themes

## Powerlevel10k theme
# RG: just a better wizard installer: Plugin 'romkatv/powerlevel10k' themes

## Auto-suggestions
Plugin 'zsh-users/zsh-autosuggestions' plugins

## Completions
Plugin 'zsh-users/zsh-completions' plugins

## Synthax highlighting
# Plugin 'zsh-users/zsh-syntax-highlighting' plugins

## History substring search
# Plugin 'zsh-users/zsh-history-substring-search' plugins

# Enabled plugins (in ~/.oh-my-zsh/custom/plugins/*)
plugins=(
    git
    python
    pyenv
    colorize
    zsh-autosuggestions
    zsh-completions
    # zsh-syntax-highlighting
    # zsh-history-substring-search
)

### Other settings

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

