#!/bin/zsh

#####################################
##  Shell prompt
#####################################

# Path to your oh-my-zsh installation.
if [ ! -d ~/.oh-my-zsh ]; then
    sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
fi
export ZSH="${HOME}/.oh-my-zsh"

# My favorite theme setter
if [ ! -d ~/.oh-my-zsh/custom/themes/powerlevel9k ]; then
    git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
fi

### Powerlevel9k theme (<3)
ZSH_THEME="powerlevel9k/powerlevel9k"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git python pyenv colorize)

POWERLEVEL9K_MODE='awesome'
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user host dir_writable dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs virtualenv anaconda pyenv)

# if powerline is not enabled
if [[ ! ${powerline} ]]; then
    POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
    POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
    POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
    POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
    POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=' '
fi

# Left prompt: user > host > dir
# ===========================================================
POWERLEVEL9K_USER_DEFAULT_BACKGROUND="cyan"
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_USER_ROOT_BACKGROUND="red"
POWERLEVEL9K_USER_ROOT_FOREGROUND="white"

POWERLEVEL9K_HOST_LOCAL_BACKGROUND="green"
POWERLEVEL9K_HOST_LOCAL_FOREGROUND="black"
POWERLEVEL9K_HOST_REMOTE_BACKGROUND="orange"
POWERLEVEL9K_HOST_REMOTE_FOREGROUND="black"

POWERLEVEL9K_DIR_WRITABLE_BACKGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_BACKGROUND="default"
POWERLEVEL9K_DIR_HOME_FOREGROUND="yellow"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="default"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="yellow"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="default"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="yellow"
POWERLEVEL9K_DIR_ETC_BACKGROUND="default"
POWERLEVEL9K_DIR_ETC_FOREGROUND="yellow"
#POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true

if [[ ${TERM} == "linux" ]]; then
    # TODO: changes all colors for linux console mode
    POWERLEVEL9K_USER_DEFAULT_BACKGROUND="none"
    POWERLEVEL9K_USER_DEFAULT_FOREGROUND="cyan"
fi

# Right prompt: status < git < virtualenv < time
# ===========================================================
POWERLEVEL9K_STATUS_OK_BACKGROUND="black"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="red"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="yellow"

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="green"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="black"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="black"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="red"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="black"

#POWERLEVEL9K_VIRTUALENV_MODIFIED_BACKGROUND="blue"
#POWERLEVEL9K_VIRTUALENV_MODIFIED_FOREGROUND="white"

POWERLEVEL9K_TIME_BACKGROUND="black"
POWERLEVEL9K_TIME_FOREGROUND="249"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"

# Newline prompt: cursor
# ===========================================================
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
if [[ ${powerline} ]]; then
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%F{red}%}\uE0B0%{%F{default}%} "
else
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%F{red}%}>%{%F{default}%} "
fi


# ===========================================================
### Others settings

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

[ -f ${ZSH}/oh-my-zsh.sh ] && source ${ZSH}/oh-my-zsh.sh
