#!/bin/zsh

#####################################
##  Shell customization
#####################################

# additional key bindings
# note: escape sequence could be '\e' or ''
bindkey "\e[1~" beginning-of-line       # [Home]
bindkey "\e[4~" end-of-line             # [End]
# for rxvt
bindkey "\e[7~" beginning-of-line       # [Home]
bindkey "\e[8~" end-of-line             # [End]
# for non RH/Debian xterm, can't hurt for RH/DEbian xterm
bindkey "\eOH" beginning-of-line        # [Home]
bindkey "\eOF" end-of-line              # [End]
# for freebsd console
bindkey "\e[H" beginning-of-line        # [Home]
bindkey "\e[F" end-of-line              # [End]
# move keys
bindkey "\e[1;5D" backward-word         # [Ctrl + LeftArrow]
bindkey "\e[1;2D" backward-word         # [Shft + LeftArrow]
bindkey "\e[1;3D" backward-word         # [Alt + LeftArrow]
bindkey "\e[1;5C" forward-word          # [Ctrl + RightArrow]
bindkey "\e[1;2C" forward-word          # [Shft + RightArrow]
bindkey "\e[1;3C" forward-word          # [Alt + RightArrow]
# delete keys
bindkey "\e[3~" delete-char             # [Delete]
bindkey "\C-h" backward-kill-word       # [Ctrl/Shft/Alt + Backspace]
bindkey "\e[3;5~" kill-word             # [Ctrl + Delete]
bindkey "\e[3;2~" kill-word             # [Shft + Delete]
bindkey "\e[3;3~" kill-word             # [Alt + Delete]

#####################################
#   Prompt
#####################################

### Default option values

# Automatic background colors and powerline font activations (only on linux).
# For manual activations:
# $ echo "export colorbg=1" >> ~/.zsh/zshrc.first
# $ echo "export powerline=1" >> ~/.zsh/zshrc.first
if [[ "$OSTYPE" == linux* ]]; then
  # no color bg in console out of X
  [[ -z "${colorbg+unset}" ]] && xrdb -query &> /dev/null && export colorbg=1
  
  # check if selected in .Xresources
  [[ -z "${powerline+unset}" ]] && xrdb -query | grep -E 'Powerline|Nerd\ Font|DejaVuSansMono\ NF' &> /dev/null && export powerline=1
fi

# activate git status by default
[[ -z "${gitstatus+unset}" ]] && export gitstatus=1

# use bell as notifier at each prompt
[[ -z "${prompt_notify+unset}" ]] && export prompt_notify=''

# oh-my-zsh fix: hide completion insecurities warning messages
[[ "$OSTYPE" == darwin* ]] && export ZSH_DISABLE_COMPFIX=true
