#!/bin/tcsh
#####################################
# Prompt coloré
# set color_name = '%{^[[ color_code m%}'
#####################################

# 16 normal foreground colors
set prompt_fg_black     = '%{^[[30m%}'
set prompt_fg_red       = '%{^[[31m%}'
set prompt_fg_green     = '%{^[[32m%}'
set prompt_fg_yellow    = '%{^[[33m%}'
set prompt_fg_blue      = '%{^[[34m%}'
set prompt_fg_magenta   = '%{^[[35m%}'
set prompt_fg_cyan      = '%{^[[36m%}'
set prompt_fg_white     = '%{^[[37m%}'
set prompt_fg_brblack   = '%{^[[90m%}'
set prompt_fg_brred     = '%{^[[91m%}'
set prompt_fg_brgreen   = '%{^[[92m%}'
set prompt_fg_bryellow  = '%{^[[93m%}'
set prompt_fg_brblue    = '%{^[[94m%}'
set prompt_fg_brmagenta = '%{^[[95m%}'
set prompt_fg_brcyan    = '%{^[[96m%}'
set prompt_fg_brwhite   = '%{^[[97m%}'
# 16 bold foreground colors
set prompt_fgb_black     = '%{^[[30;1m%}'
set prompt_fgb_red       = '%{^[[31;1m%}'
set prompt_fgb_green     = '%{^[[32;1m%}'
set prompt_fgb_yellow    = '%{^[[33;1m%}'
set prompt_fgb_blue      = '%{^[[34;1m%}'
set prompt_fgb_magenta   = '%{^[[35;1m%}'
set prompt_fgb_cyan      = '%{^[[36;1m%}'
set prompt_fgb_white     = '%{^[[37;1m%}'
set prompt_fgb_brblack   = '%{^[[90;1m%}'
set prompt_fgb_brred     = '%{^[[91;1m%}'
set prompt_fgb_brgreen   = '%{^[[92;1m%}'
set prompt_fgb_bryellow  = '%{^[[93;1m%}'
set prompt_fgb_brblue    = '%{^[[94;1m%}'
set prompt_fgb_brmagenta = '%{^[[95;1m%}'
set prompt_fgb_brcyan    = '%{^[[96;1m%}'
set prompt_fgb_brwhite   = '%{^[[97;1m%}'
# 16 background colors
set prompt_bg_black     = '%{^[[40m%}'
set prompt_bg_red       = '%{^[[41m%}'
set prompt_bg_green     = '%{^[[42m%}'
set prompt_bg_yellow    = '%{^[[43m%}'
set prompt_bg_blue      = '%{^[[44m%}'
set prompt_bg_magenta   = '%{^[[45m%}'
set prompt_bg_cyan      = '%{^[[46m%}'
set prompt_bg_white     = '%{^[[47m%}'
set prompt_bg_brblack   = '%{^[[100m%}'
set prompt_bg_brred     = '%{^[[101m%}'
set prompt_bg_brgreen   = '%{^[[102m%}'
set prompt_bg_bryellow  = '%{^[[103m%}'
set prompt_bg_brblue    = '%{^[[104m%}'
set prompt_bg_brmagenta = '%{^[[105m%}'
set prompt_bg_brcyan    = '%{^[[106m%}'
set prompt_bg_brwhite   = '%{^[[107m%}'
# customized colors
set prompt_fg_orange     = "${prompt_fg_brred}"
set prompt_fg_violet     = "${prompt_fg_brmagenta}"
set prompt_bg_orange     = "${prompt_bg_brred}"
set prompt_bg_violet     = "${prompt_bg_brmagenta}"
# special colors
set prompt_restore = '%{^[[0;0m%}'
set prompt_bg_fillline = '%{^[[J%}'

# 16 normal foreground colors
set termcap_fg_black     = '[0;30m'
set termcap_fg_red       = '[0;31m'
set termcap_fg_green     = '[0;32m'
set termcap_fg_yellow    = '[0;33m'
set termcap_fg_blue      = '[0;34m'
set termcap_fg_magenta   = '[0;35m'
set termcap_fg_cyan      = '[0;36m'
set termcap_fg_white     = '[0;37m'
set termcap_fg_brblack   = '[0;90m'
set termcap_fg_brred     = '[0;91m'
set termcap_fg_brgreen   = '[0;92m'
set termcap_fg_bryellow  = '[0;93m'
set termcap_fg_brblue    = '[0;94m'
set termcap_fg_brmagenta = '[0;95m'
set termcap_fg_brcyan    = '[0;96m'
set termcap_fg_brwhite   = '[0;97m'
# 16 bold foreground colors
set termcap_fgb_black     = '[1;30m'
set termcap_fgb_red       = '[1;31m'
set termcap_fgb_green     = '[1;32m'
set termcap_fgb_yellow    = '[1;33m'
set termcap_fgb_blue      = '[1;34m'
set termcap_fgb_magenta   = '[1;35m'
set termcap_fgb_cyan      = '[1;36m'
set termcap_fgb_white     = '[1;37m'
set termcap_fgb_brblack   = '[1;90m'
set termcap_fgb_brred     = '[1;91m'
set termcap_fgb_brgreen   = '[1;92m'
set termcap_fgb_bryellow  = '[1;93m'
set termcap_fgb_brblue    = '[1;94m'
set termcap_fgb_brmagenta = '[1;95m'
set termcap_fgb_brcyan    = '[1;96m'
set termcap_fgb_brwhite   = '[1;97m'
# 16 background colors
set termcap_bg_black     = '[40m'
set termcap_bg_red       = '[41m'
set termcap_bg_green     = '[42m'
set termcap_bg_yellow    = '[43m'
set termcap_bg_blue      = '[44m'
set termcap_bg_magenta   = '[45m'
set termcap_bg_cyan      = '[46m'
set termcap_bg_white     = '[47m'
set termcap_bg_brblack   = '[100m'
set termcap_bg_brred     = '[101m'
set termcap_bg_brgreen   = '[102m'
set termcap_bg_bryellow  = '[103m'
set termcap_bg_brblue    = '[104m'
set termcap_bg_brmagenta = '[105m'
set termcap_bg_brcyan    = '[106m'
set termcap_bg_brwhite   = '[107m'
# customized colors
set termcap_fg_orange     = "${termcap_fg_brred}"
set termcap_fg_violet     = "${termcap_fg_brmagenta}"
set termcap_bg_orange     = "${termcap_bg_brred}"
set termcap_bg_violet     = "${termcap_bg_brmagenta}"
# special colors
set termcap_restore = '[0;0m'
set termcap_bg_fillline = '[J'

# define user foreground/background colors
if ( ${?root} ) then
  set prompt_fg_usr   = "${prompt_fg_red}"
  set prompt_fgb_usr  = "${prompt_fgb_red}"
  set prompt_bg_usr   = "${prompt_bg_red}"
  set termcap_fg_usr  = "${termcap_fg_red}"
  set termcap_fgb_usr = "${termcap_fgb_red}"
  set termcap_bg_usr  = "${termcap_bg_red}"
else
  set prompt_fg_usr   = "${prompt_fg_cyan}"
  set prompt_fgb_usr  = "${prompt_fgb_cyan}"
  set prompt_bg_usr   = "${prompt_bg_cyan}"
  set termcap_fg_usr  = "${termcap_fg_cyan}"
  set termcap_fgb_usr = "${termcap_fgb_cyan}"
  set termcap_bg_usr  = "${termcap_bg_cyan}"
endif

