#!/bin/tcsh

#####################################
##  Shell customization
#####################################

set history=( 100000 "%h [%Y-%W-%D %T] %R\n" )
set savehist=100000
set time=10

set histlit
set filec
set nobeep
set implicitcd
set color
set noding
set dextract
set dunique

alias helpcommand '\!* -h'

# keyboard
bindkey -s " " '`/usr/bin/printf "\\u00A0"`'

# additional key bindings
# note: escape sequence could be '\e' or ''
bindkey "^N" history-search-forward     # [Ctrl + N]
bindkey "^P" history-search-backward    # [Ctrl + P]
bindkey "^R" i-search-back              # [Ctrl + R]
bindkey "^W" backward-delete-word       # [Ctrl + W]
bindkey "\e[4~" end-of-line             # [End]
bindkey "\e[1~" beginning-of-line       # [Home]
bindkey "\e[A" history-search-backward  # [Up]
bindkey "\e[B" history-search-forward   # [Down]
# move keys
bindkey "\e[1;5D" backward-word         # [Ctrl + LeftArrow]
bindkey "\e[1;2D" backward-word         # [Shft + LeftArrow]
bindkey "\e[1;3D" backward-word         # [Alt + LeftArrow]
bindkey "\e[1;5C" forward-word          # [Ctrl + RightArrow]
bindkey "\e[1;2C" forward-word          # [Shft + RightArrow]
bindkey "\e[1;3C" forward-word          # [Alt + RightArrow]
# delete keys
bindkey "\e[3~" delete-char             # [Delete]
bindkey "^H" backward-delete-word       # [Ctrl/Shft/Alt + Backspace]
bindkey "\e[3;5~" delete-word           # [Ctrl + Delete]
bindkey "\e[3;2~" delete-word           # [Shft + Delete]
bindkey "\e[3;3~" delete-word           # [Alt + Delete]

# other keys
bindkey "." insert-last-word
bindkey -c "z" "fg"

#####################################
##  Auto-completion
#####################################

set autolist=ambiguous
set autocorrect
set autoexpand
set complete=enhance
set correct=cmd
#RG: do no use!!: set symlinks=chase

## <tab> | make cycle forward between possible completions
#bindkey "\t" complete-word-fwd
## <S-tab> | make cycle backward between possible completions
#bindkey "\e[Z" complete-word-back

# CSH autocompletion features
[ -f "${HOME}/.csh/completion" ] && source ${HOME}/.csh/completion

# Git autocompletion features (already source in 'completion')
# (https://github.com/git/git/blob/master/contrib/completion/git-completion.tcsh)
#[ -f "${HOME}/.csh/git-completion.tcsh" ] && source ${HOME}/.csh/git-completion.tcsh

#####################################
##  Prompt
#####################################

#====================================
#  Default option values
#====================================

# Automatic background colors and powerline font activations (only on linux).
# For manual activations:
# $ echo "setenv colorbg 1" >> ~/.csh/cshrc.first
# $ echo "setenv powerline 1" >> ~/.csh/cshrc.first
if ( "$OSTYPE" =~ "darwin*" ) then
  # no color bg in console out of X
  if ( ! ${?colorbg} ) then
      (xrdb -query) >& /dev/null && setenv colorbg 1 || setenv colorbg 0
  endif
  
  # check if selected in .Xresources
  if ( ! ${?powerline} ) then
      (xrdb -query | grep -E 'Powerline|Nerd\ Font|DejaVuSansMono\ NF') >& /dev/null && setenv powerline 1 || setenv powerline 0
  endif
endif

# activate git status by default
if ( ! ${?gitstatus} ) then
    setenv gitstatus 1
endif

# use bell as notifier at each prompt
if ( ! ${?prompt_notify} ) then
    setenv prompt_notify ''
endif

# disable automatic virtual environment print on prompt
setenv VIRTUAL_ENV_DISABLE_PROMPT 1

# Special keys for every terminals
if (${?STY}) then # we are in a screen session
  set vt_dcs = "\033P"                     ; #escape string using DCS (Display Control String)
  set vt_st = "\033\\"                     ;
  set vt_fg = "\033]10"
  set vt_bg = "\033]11"
  set vt_ct = "\007"
  set vt_co = "\033]4"
else if (${?TMUX}) then # we are in a tmux session
  set vt_dcs = "\033Ptmux;"                ; #escape string using DCS (Display Control String)
  set vt_st = "\033\\"                     ;
  set vt_fg = "\033\033]10"
  set vt_bg = "\033\033]11"
  set vt_ct = "\007"
  set vt_co = "\033\033]4"
else
  set vt_dcs = ""                        ;
  set vt_st = ""                         ;
  set vt_fg = "\033]10"
  set vt_bg = "\033]11"
  set vt_ct = "\007"
  set vt_co = "\033]4"
endif

set ctlhead = "${vt_dcs}"
set ctltail = "${vt_ct}${vt_st}"

#====================================
#  Default themes
#====================================

# /!\ DO NOT CHANGE HERE, USE THOSE VARIABLES IN YOUR ~/.csh/cshrc.perso /!\
set themes_dir="${HOME}/.themes"
if ( ! ${?background} )  set background  = "dark"
if ( ! ${?dark_theme} )  set dark_theme  = "roman-dark"
if ( ! ${?light_theme} ) set light_theme = "solarized-light"
if ( ${background} == "dark" ) then
    set current_theme = "${dark_theme}"
else
    set current_theme = "${light_theme}"
endif

# Parsing them colors from theme file (*.sh)
foreach line ("`grep -E ^export ${themes_dir}/${current_theme}.sh`")
  # extract color and label name from file
  set label          = `echo $line | perl -pe 's/export\s+([^ =]+)=.*/\1/g'`
  set hex_color      = `echo $line | perl -pe 's/export.+="#(.{2})(.{2})(.{2})".*/\1\/\2\/\3/g'`
  ## foreground color
  if ( ${label} == "FOREGROUND_COLOR" ) printf "${ctlhead}${vt_fg};rgb:${hex_color}${ctltail}"
  ## background color
  if ( ${label} == "BACKGROUND_COLOR" ) printf "${ctlhead}${vt_bg};rgb:${hex_color}${ctltail}"
  ## other colors
  if ( "${label}" =~ "COLOR_*" ) then
    set number = `echo ${label} | cut -d '_' -f2`
    set number = `echo ${number} - 1 | bc`
    printf "${ctlhead}${vt_co};${number};rgb:${hex_color}${ctltail}"
  endif
end

# <F5> to toggle :D
bindkey -c "[15~" "source ~/.csh/toggle_background"

source ~/.csh/prompt
